name: pages

on:
  push:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create public directory
        run: 'mkdir public'

      - name: Get current commit SHA
        id: commit_sha
        run: 'echo "::set-output name=sha::${{ github.sha }}"'

      - name: Write commit SHA to index.html
        run: 'echo "Commit SHA: ${{ steps.commit_sha.outputs.sha }}" > public/index.html'

      - name: Deploy Page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_dir: public
          publish_branch: gh-pages
          # keep_files: true
          destination_dir: ${{ github.ref_name }}
